In [1]:
from mostlyai import MostlyAI
import pandas as pd
from tsl.datasets import AirQuality, MetrLA, PemsBay
from sklearn.model_selection import train_test_split
from Metrics import evaluate_datasets

TeachForcing_path = '/Users/paulmagos/Documents/TSGen/Datasets/TeachForcingDatasets/'
Precition_path = '/Users/paulmagos/Documents/TSGen/Datasets/PredictedDatasets/'

In [2]:
df_PemsBay = PemsBay()
df_PemsBay = df_PemsBay.dataframe()[-1000:].reset_index(drop=True)

df_MetrLA = MetrLA()
df_MetrLA = df_MetrLA.dataframe()[-1000:].reset_index(drop=True)

df_AirQuality = AirQuality(impute_nans=True, small=True)
df_AirQuality = df_AirQuality.dataframe()[-1000:].reset_index(drop=True)

df_PemsBay['gen'] = 1
df_MetrLA['gen'] = 1
df_AirQuality['gen'] = 1

df_PemsBay.columns = df_PemsBay.columns.droplevel('channels')
df_MetrLA.columns = df_MetrLA.columns.droplevel('channels')
df_AirQuality.columns = df_AirQuality.columns.droplevel('channels')

/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/tsl/datasets/pems_bay.py:84: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(df.index[0], df.index[-1], freq='5T')
/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/tsl/datasets/pems_bay.py:96: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=0, inplace=True)
/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/tsl/datasets/metr_la.py:98: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(df.index[0], df.index[-1], freq='5T')
/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')

In [3]:
# split into training and validation
df_Pems_trn, df_Pems_hol = train_test_split(df_PemsBay, test_size=0.2, random_state=1)

print(f'training data with {df_Pems_trn.shape[0]:,} records and {df_Pems_trn.shape[1]} attributes')
print(f'holdout data with {df_Pems_hol.shape[0]:,} records and {df_Pems_hol.shape[1]} attributes')


df_Metr_trn, df_Metr_hol = train_test_split(df_MetrLA, test_size=0.2, random_state=1)

print(f'training data with {df_Metr_trn.shape[0]:,} records and {df_Metr_trn.shape[1]} attributes')
print(f'holdout data with {df_Metr_hol.shape[0]:,} records and {df_Metr_hol.shape[1]} attributes')

df_Air_trn, df_Air_hol = train_test_split(df_AirQuality, test_size=0.2, random_state=1)

print(f'training data with {df_Air_trn.shape[0]:,} records and {df_Air_trn.shape[1]} attributes')
print(f'holdout data with {df_Air_hol.shape[0]:,} records and {df_Air_hol.shape[1]} attributes')

training data with 800 records and 326 attributes
holdout data with 200 records and 326 attributes
training data with 800 records and 208 attributes
holdout data with 200 records and 208 attributes
training data with 800 records and 37 attributes
holdout data with 200 records and 37 attributes

In [4]:
syn_MetrLA_GTM = pd.read_csv(f'{TeachForcing_path}TeachForcingMetrLAGTM.csv')
syn_PemsBay_GTM = pd.read_csv(f'{TeachForcing_path}TeachForcingPemsBayGTM.csv')
syn_AirQuality_GTM = pd.read_csv(f'{TeachForcing_path}TeachForcingAirQualityGTM.csv')

syn_MetrLA_GTM['gen'] = 0
syn_PemsBay_GTM['gen'] = 0
syn_AirQuality_GTM['gen'] = 0


syn_MetrLA_GTLSTM = pd.read_csv(f'{TeachForcing_path}TeachForcingMetrLAGTLSTM.csv')
syn_PemsBay_GTLSTM = pd.read_csv(f'{TeachForcing_path}TeachForcingPemsBayGTLSTM.csv')
syn_AirQuality_GTLSTM = pd.read_csv(f'{TeachForcing_path}TeachForcingAirQualityGTLSTM.csv')

syn_MetrLA_GTLSTM['gen'] = 0
syn_PemsBay_GTLSTM['gen'] = 0
syn_AirQuality_GTLSTM['gen'] = 0

syn_MetrLA_GRGN = pd.read_csv(f'{TeachForcing_path}TeachForcingMetrLAGRGN.csv')
syn_PemsBay_GRGN = pd.read_csv(f'{TeachForcing_path}TeachForcingPemsBayGRGN2.csv')
syn_AirQuality_GRGN = pd.read_csv(f'{TeachForcing_path}TeachForcingAirQualityGRGN.csv')

syn_MetrLA_GRGN['gen'] = 0
syn_PemsBay_GRGN['gen'] = 0
syn_AirQuality_GRGN['gen'] = 0

Predicted_MetrLA_GRIN = pd.read_csv(f'{Precition_path}GRINMetrLAPrediction.csv')
Predicted_PemsBay_GRIN = pd.read_csv(f'{Precition_path}GRINPemsBayPrediction.csv')
Predicted_AirQuality_GRIN = pd.read_csv(f'{Precition_path}GRINAirQualityPrediction.csv')

Predicted_MetrLA_GRIN['gen'] = 0
Predicted_PemsBay_GRIN['gen'] = 0
Predicted_AirQuality_GRIN['gen'] = 0

In [5]:
results_df = pd.DataFrame(columns=['dataset', 'model', 'mean_difference',
 'variance_difference',
 'skewness_difference',
 'kurtosis_difference',
 'ks_test',
 'ks_test_p_value',
 'wasserstein_distance',
 'js_divergence',
 'correlation_difference',
 'mmd_linear',
 'mmd_rbf',
 'mmd_poly',
 'model_accuracy',
 'model_accuracy_on_Gen',
 'model_accuracy_train_on_both',
 'model_accuracy_train_on_both_Gen'])

In [6]:
df_PemsBay.columns = [str(col) for col in df_PemsBay.columns]
df_MetrLA.columns = [str(col) for col in df_MetrLA.columns]
df_AirQuality.columns = [str(col) for col in df_AirQuality.columns]

syn_PemsBay_GTM.columns = [str(col) for col in syn_PemsBay_GTM.columns]
syn_MetrLA_GTM.columns = [str(col) for col in syn_MetrLA_GTM.columns]
syn_AirQuality_GTM.columns = [str(col) for col in syn_AirQuality_GTM.columns]

syn_AirQuality_GTLSTM.columns = [str(col) for col in syn_AirQuality_GTLSTM.columns]
syn_PemsBay_GTLSTM.columns = [str(col) for col in syn_PemsBay_GTLSTM.columns]
syn_MetrLA_GTLSTM.columns = [str(col) for col in syn_MetrLA_GTLSTM.columns]

syn_MetrLA_GRGN.columns = [str(col) for col in syn_MetrLA_GRGN.columns]
syn_PemsBay_GRGN.columns =  [str(col) for col in syn_PemsBay_GRGN.columns]
syn_AirQuality_GRGN.columns =  [str(col) for col in syn_AirQuality_GRGN.columns]

In [7]:
# out = evaluate_datasets(df_PemsBay, df_PemsBay, 'gen')
# out['dataset'] = "PemsBay Original"
# res = pd.DataFrame(out, ["PemsBay Original"])
# results_df = pd.concat([results_df, res], ignore_index = True)

# out = evaluate_datasets(df_MetrLA, df_MetrLA, 'gen')
# out['dataset'] = "MetrLA Original"
# res = pd.DataFrame(out, ["MetrLA Original"])
# results_df = pd.concat([results_df, res], ignore_index = True)

# out = evaluate_datasets(df_AirQuality, df_AirQuality, 'gen')
# out['dataset'] = "AirQuality Original"
# res = pd.DataFrame(out, ["AirQuality Original"])
# results_df = pd.concat([results_df, res], ignore_index = True)

In [8]:
out = evaluate_datasets(df_PemsBay, syn_PemsBay_GTM, 'gen')
out['dataset'] = "PemsBay"
out['model'] = "GTM"
res = pd.DataFrame(out, ["PemsBay GTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

out = evaluate_datasets(df_MetrLA, syn_MetrLA_GTM, 'gen')
out['dataset'] = "MetrLA"
out['model'] = "GTM"
res = pd.DataFrame(out, ["MetrLA GTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

out = evaluate_datasets(df_AirQuality, syn_AirQuality_GTM, 'gen')
out['dataset'] = "AirQuality"
out['model'] = "GTM"
res = pd.DataFrame(out, ["AirQuality GTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/var/folders/2f/0xjdq0xn6b3cfw3v2k2svn3m0000gn/T/ipykernel_5349/4208765438.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, res], ignore_index = True)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)

In [9]:
out = evaluate_datasets(df_PemsBay, syn_PemsBay_GTLSTM, 'gen')
out['dataset'] = "PemsBay"
out['model'] = "GTLSTM"
res = pd.DataFrame(out, ["PemsBay GTLSTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

out = evaluate_datasets(df_MetrLA, syn_MetrLA_GTLSTM, 'gen')
out['dataset'] = "MetrLA"
out['model'] = "GTLSTM"
res = pd.DataFrame(out, ["MetrLA GTLSTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

out = evaluate_datasets(df_AirQuality, syn_AirQuality_GTLSTM, 'gen')
out['dataset'] = "AirQuality"
out['model'] = "GTLSTM"
res = pd.DataFrame(out, ["AirQuality GTLSTM"])
results_df = pd.concat([results_df, res], ignore_index = True)

/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)

In [10]:
out = evaluate_datasets(df_PemsBay, syn_PemsBay_GRGN, 'gen')
out['dataset'] = "PemsBay"
out['model'] = "GRGN"
res = pd.DataFrame(out, ["PemsBay GRGN"])
results_df = pd.concat([results_df, res], ignore_index = True)


out = evaluate_datasets(df_MetrLA, syn_MetrLA_GRGN, 'gen')
out['dataset'] = "MetrLA"
out['model'] = "GRGN"
res = pd.DataFrame(out, ["MetrLA GRGN"])
results_df = pd.concat([results_df, res], ignore_index = True)


out = evaluate_datasets(df_AirQuality, syn_AirQuality_GRGN, 'gen')
out['dataset'] = "AirQuality"
out['model'] = "GRGN"
res = pd.DataFrame(out, ["AirQuality GRGN"])
results_df = pd.concat([results_df, res], ignore_index = True)

/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)

In [11]:
out = evaluate_datasets(df_PemsBay, Predicted_PemsBay_GRIN, 'gen')
out['dataset'] = "PemsBay"
out['model'] = "GRIN"
res = pd.DataFrame(out, ["PemsBay GRIN"])
results_df = pd.concat([results_df, res], ignore_index = True)


out = evaluate_datasets(df_MetrLA, Predicted_MetrLA_GRIN, 'gen')
out['dataset'] = "MetrLA"
out['model'] = "GRIN"
res = pd.DataFrame(out, ["MetrLA GRIN"])
results_df = pd.concat([results_df, res], ignore_index = True)


out = evaluate_datasets(df_AirQuality, Predicted_AirQuality_GRIN, 'gen')
out['dataset'] = "AirQuality"
out['model'] = "GRIN"
res = pd.DataFrame(out, ["AirQuality GRIN"])
results_df = pd.concat([results_df, res], ignore_index = True)

/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:44: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  'skewness': [np.abs(skew(df_original[column]) - skew(df_generated[column]))],
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:45: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  'kurtosis': [np.abs(kurtosis(df_original[column]) - kurtosis(df_generated[column]))]
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py:605: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, axis=axis, **kwds)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:44: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  'skewness': [np.abs(skew(df_original[column]) - skew(df_generated[column]))],
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:45: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  'kurtosis': [np.abs(kurtosis(df_original[column]) - kurtosis(df_generated[column]))]
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/.pyenv/versions/3.11.9/envs/Dopple/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py:605: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, axis=axis, **kwds)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stats = pd.concat([stats, pd.DataFrame({
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ks_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:73: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wasserstein_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  js_results = pd.concat([
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: divide by zero encountered in log
  kl_div = split_preds * np.log(split_preds / marginal)
/Users/paulmagos/Documents/TSGen/Notebooks/Metrics.py:147: RuntimeWarning: invalid value encountered in multiply
  kl_div = split_preds * np.log(split_preds / marginal)

In [12]:
results_df = results_df.sort_values(by='mmd_linear').reset_index(drop=True)
results_df[results_df['dataset'] == 'MetrLA']

,dataset,model,mean_difference,variance_difference,skewness_difference,kurtosis_difference,ks_test,ks_test_p_value,wasserstein_distance,js_divergence,...,mmd_rbf,mmd_poly,model_accuracy,model_accuracy_on_Gen,model_accuracy_train_on_both,model_accuracy_train_on_both_Gen,inception_score_mean,inception_score_std,t_stat,t_stat_p_value
4,MetrLA,GRIN,2.100100,62.758822,1.290614,16.000420,0.230236,1.467197e-06,3.117428,0.311258,...,0.019444,NaN,0.0,0.0,0.992,1.0,1.356135,0.678366,-4.537812,0.069830
6,MetrLA,GTLSTM,2.732190,114.022991,2.211501,8.180405,0.450312,1.903052e-08,6.114224,0.614248,...,0.029450,NaN,0.0,0.0,1.000,1.0,0.595297,0.909332,-0.619286,0.065245
10,MetrLA,GTM,4.323815,53.714127,1.941160,7.393603,0.320763,9.668278e-05,5.983050,0.685032,...,0.002096,NaN,0.0,0.0,1.000,1.0,0.000000,0.000000,-2.081344,0.027905
11,MetrLA,GRGN,4.704967,457.520964,2.238577,8.694813,0.392715,9.089599e-45,14.820494,0.634796,...,0.002096,NaN,0.0,0.0,1.000,1.0,0.794391,0.972946,-0.868781,0.073451

In [13]:
results_df['tmp'] = results_df['mean_difference'] + results_df['variance_difference']

In [21]:
results_df = results_df.sort_values(by=['mmd_rbf']).reset_index(drop=True)
results_df

,dataset,model,mean_difference,variance_difference,skewness_difference,kurtosis_difference,ks_test,ks_test_p_value,wasserstein_distance,js_divergence,...,mmd_poly,model_accuracy,model_accuracy_on_Gen,model_accuracy_train_on_both,model_accuracy_train_on_both_Gen,inception_score_mean,inception_score_std,t_stat,t_stat_p_value,tmp
0,AirQuality,GRIN,3.731027,1437.983901,0.547809,2.073271,0.124639,7.088841e-05,11.425218,0.169096,...,NaN,0.0,0.0,0.476,0.992486,0.000000,0.000000,1.021193,0.354973,1441.714928
1,PemsBay,GRIN,1.910370,56.773380,0.896311,6.462122,0.279729,1.214503e-03,2.840759,0.374524,...,NaN,0.0,0.0,1.000,1.000000,1.702985,0.034193,-1.107681,0.097666,58.683751
2,PemsBay,GRGN,3.270937,97.717162,2.238661,8.157078,0.525289,3.215334e-13,6.147888,0.622257,...,NaN,0.0,0.0,1.000,1.000000,0.000000,0.000000,8.775906,0.035564,100.988099
3,AirQuality,GRGN,8.110985,2399.165217,1.057422,1.955987,0.425028,3.592759e-55,33.209360,0.533192,...,NaN,0.0,0.0,0.966,1.000000,0.000000,0.000000,2.930005,0.066377,2407.276202
4,MetrLA,GTM,4.323815,53.714127,1.941160,7.393603,0.320763,9.668278e-05,5.983050,0.685032,...,NaN,0.0,0.0,1.000,1.000000,0.000000,0.000000,-2.081344,0.027905,58.037942
5,MetrLA,GRGN,4.704967,457.520964,2.238577,8.694813,0.392715,9.089599e-45,14.820494,0.634796,...,NaN,0.0,0.0,1.000,1.000000,0.794391,0.972946,-0.868781,0.073451,462.225931
6,PemsBay,GTM,1.938705,171.762852,1.921164,7.496421,0.298519,6.885741e-06,6.521830,0.622777,...,NaN,0.0,0.0,1.000,1.000000,1.900244,0.025658,0.615191,0.157694,173.701557
7,PemsBay,GTLSTM,3.355599,92.338557,2.087390,7.718859,0.502320,4.443758e-07,5.882983,0.586812,...,NaN,0.0,0.0,1.000,1.000000,1.590874,0.795458,1.042225,0.046539,95.694156
8,AirQuality,GTM,11.811962,1350.150414,0.343568,1.694042,0.266717,3.775109e-04,19.118943,0.378897,...,NaN,0.0,0.0,0.900,0.947720,0.365250,0.730501,-5.824113,0.090367,1361.962376
9,AirQuality,GTLSTM,7.111527,1046.819169,0.348541,1.959327,0.138398,5.967616e-03,10.960778,0.252239,...,NaN,0.0,0.0,0.961,0.992214,0.000000,0.000000,1.194029,0.172821,1053.930696
10,MetrLA,GRIN,2.100100,62.758822,1.290614,16.000420,0.230236,1.467197e-06,3.117428,0.311258,...,NaN,0.0,0.0,0.992,1.000000,1.356135,0.678366,-4.537812,0.069830,64.858922
11,MetrLA,GTLSTM,2.732190,114.022991,2.211501,8.180405,0.450312,1.903052e-08,6.114224,0.614248,...,NaN,0.0,0.0,1.000,1.000000,0.595297,0.909332,-0.619286,0.065245,116.755180

In [15]:
results_df.to_csv('results.csv', index=False)

In [16]:
df = results_df

# Filter for models that contain "GRGN" in the dataset
# grgn_models = df[df['dataset'].str.contains("GRGN")]
grgn_models = results_df
# Metrics to focus on
metrics_to_compare = ['mean_difference', 'variance_difference', 'ks_test', 'wasserstein_distance', 
                      'js_divergence', 'correlation_difference', 'model_accuracy', 'inception_score_mean']

# Find the minimum for distance-based metrics and the maximum for accuracy/inception-based metrics
best_grgn_models = grgn_models.loc[:, ['dataset', 'model'] + metrics_to_compare].copy()

# For distance-based metrics, lower is better, so we will look for the minimum values.
# For accuracy-based and inception score-based metrics, higher is better.

# Normalize each metric: for distance-based (lower is better), for accuracy-based (higher is better)
for col in ['mean_difference', 'variance_difference', 'ks_test', 'wasserstein_distance', 
            'js_divergence', 'correlation_difference']:
    best_grgn_models[col + '_rank'] = best_grgn_models[col].rank(ascending=True)

# For accuracy and inception score, higher is better
for col in ['model_accuracy', 'inception_score_mean']:
    best_grgn_models[col + '_rank'] = best_grgn_models[col].rank(ascending=False)

# Calculate total rank
best_grgn_models['total_rank'] = best_grgn_models[[col + '_rank' for col in metrics_to_compare]].sum(axis=1)

# Sort by total rank to find the best overall GRGN model
best_grgn_models = best_grgn_models.sort_values('total_rank').reset_index(drop=True)

# Display the best GRGN model
best_grgn_models

,dataset,model,mean_difference,variance_difference,ks_test,wasserstein_distance,js_divergence,correlation_difference,model_accuracy,inception_score_mean,mean_difference_rank,variance_difference_rank,ks_test_rank,wasserstein_distance_rank,js_divergence_rank,correlation_difference_rank,model_accuracy_rank,inception_score_mean_rank,total_rank
0,PemsBay,GRIN,1.910370,56.773380,0.279729,2.840759,0.374524,0.233204,0.0,1.702985,1.0,2.0,5.0,1.0,4.0,5.0,6.5,2.0,26.5
1,MetrLA,GRIN,2.100100,62.758822,0.230236,3.117428,0.311258,0.259236,0.0,1.356135,3.0,3.0,3.0,2.0,3.0,6.0,6.5,4.0,30.5
2,PemsBay,GTM,1.938705,171.762852,0.298519,6.521830,0.622777,0.310803,0.0,1.900244,2.0,7.0,6.0,7.0,10.0,7.0,6.5,1.0,46.5
3,AirQuality,GRIN,3.731027,1437.983901,0.124639,11.425218,0.169096,0.158008,0.0,0.000000,7.0,11.0,1.0,9.0,1.0,1.0,6.5,10.0,46.5
4,MetrLA,GTM,4.323815,53.714127,0.320763,5.983050,0.685032,0.211923,0.0,0.000000,8.0,1.0,7.0,4.0,12.0,2.0,6.5,10.0,50.5
5,PemsBay,GTLSTM,3.355599,92.338557,0.502320,5.882983,0.586812,0.488589,0.0,1.590874,6.0,4.0,11.0,3.0,7.0,11.0,6.5,3.0,51.5
6,AirQuality,GTLSTM,7.111527,1046.819169,0.138398,10.960778,0.252239,0.228454,0.0,0.000000,10.0,9.0,2.0,8.0,2.0,4.0,6.5,10.0,51.5
7,MetrLA,GTLSTM,2.732190,114.022991,0.450312,6.114224,0.614248,0.349951,0.0,0.595297,4.0,6.0,10.0,5.0,8.0,9.0,6.5,6.0,54.5
8,MetrLA,GRGN,4.704967,457.520964,0.392715,14.820494,0.634796,0.220906,0.0,0.794391,9.0,8.0,8.0,10.0,11.0,3.0,6.5,5.0,60.5
9,PemsBay,GRGN,3.270937,97.717162,0.525289,6.147888,0.622257,0.385929,0.0,0.000000,5.0,5.0,12.0,6.0,9.0,10.0,6.5,10.0,63.5
10,AirQuality,GTM,11.811962,1350.150414,0.266717,19.118943,0.378897,0.333919,0.0,0.365250,12.0,10.0,4.0,11.0,5.0,8.0,6.5,7.0,63.5
11,AirQuality,GRGN,8.110985,2399.165217,0.425028,33.209360,0.533192,0.735610,0.0,0.000000,11.0,12.0,9.0,12.0,6.0,12.0,6.5,10.0,78.5